#!/bin/sh

set -e

if [ $# != 1 ]; then
  echo >&2 "Path to .xcodeproj required"
  exit 1
fi

pbxproj="$1/project.pbxproj"

if [ ! -f "$pbxproj" ]; then
  echo >&2 "Couldn't find $pbxproj"
  exit 1
fi

ruby -p -i -e 'gsub(
  %r{name = (\w+\.framework); path = ("?).+/\1\2; sourceTree = "<(group|absolute)>"},
  "path = \\1; sourceTree = BUILT_PRODUCTS_DIR"
)' -- "$pbxproj"
